### ISSUE TITLE
运行中报错

### ISSUE THREAD

**Issue by RAINighty** [summerkirakira/biliRecorder#3]
2022-10-11 00:36:45.369 | ERROR    | services.downloader:_download:133 - 下载出错，正在重试
2022-10-11 00:36:45.371 | ERROR    | services.downloader:_download:134 -
Traceback (most recent call last):

> File "/root/storage/biliRecorder/services/downloader.py", line 122, in _download
    async for chunk in response.content.iter_chunked(1024):
              │        │        │       └ <function AsyncStreamReaderMixin.iter_chunked at 0x7f1eabffae60>
              │        │        └ <StreamReader e=ClientConnectionError('Connection closed')>
              │        └ <ClientResponse(https://0gr4uqmtt8y41hcjsgrzdrctu.ourdvsss.com/d1--ov-gotcha05.bilivideo.com/live-bvc/127106/live_8937568_795...
              └ b'H"\rM\xe6X\xe7\xe0\x11\xec\t\xb9\xd2\xb8g\xc4\xea%\x13G\xc5T\xefAv\x14D{_,5\xd5\xcc\xaa*\xcd\x0c\xfc\xef\xcbT\x8a\xe7\x17\x...

  File "/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py", line 35, in __anext__
    rv = await self.read_func()
               │    └ <function AsyncStreamReaderMixin.iter_chunked.<locals>.<lambda> at 0x7f1ea95e2dd0>
               └ <aiohttp.streams.AsyncStreamIterator object at 0x7f1ea98ac640>
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py", line 385, in read
    await self._wait("read")
          │    └ <function StreamReader._wait at 0x7f1eabffb7f0>
          └ <StreamReader e=ClientConnectionError('Connection closed')>
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py", line 303, in _wait
    with self._timer:
         │    └ <aiohttp.helpers.TimerContext object at 0x7f1ea98acaf0>
         └ <StreamReader e=ClientConnectionError('Connection closed')>
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/helpers.py", line 720, in __exit__
    raise asyncio.TimeoutError from None
          │       └ <class 'asyncio.exceptions.TimeoutError'>
          └ <module 'asyncio' from '/usr/lib/python3.10/asyncio/__init__.py'>

asyncio.exceptions.TimeoutError
2022-10-11 00:36:45.375 | ERROR    | services.downloader:_download:135 - 重新获取推流地址中...
经常出现，似乎不影响视频合成

以及出现了直播还没播完，且没断流的情况下认为直播间准备中然后渲染视频的问题

**Comment by RAINighty** [comment]
而且视频似乎还没有上传，是否与cookie值为null有关

**Comment by summerkirakira** [comment]
断流是正常情况，提前渲染视频的情况可以提供一下日志吗

**Comment by laotang8** [comment]
有没有交流群，或者联系方式啊，想具体了解一下
